version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-application
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: user_accounts
      DISPLAY: $DISPLAY  # Set the DISPLAY environment variable
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 Unix domain socket
      - /dev/dri:/dev/dri
    networks:
      - app-network
  db:
    image: postgres:13.4
    container_name: my-db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_accounts
    expose:
      - "1234"
    ports:
      - "1234:1234"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:

